from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.display, name='home'),
    url(r'^contact/', views.contact, name='contact'),
    url(r'^gallery/', views.gallery, name='gallery'),
    url(r'^payments/', views.payments, name='payments'),
    url(r'^login/', views.login_page, name='login_page'),
    url(r'^login_now/', views.login_now, name='login_now'),
    url(r'^logout_now/$', views.logout_now, name='logout_now'),
    url(r'^profile/', views.profile, name='profile'),
    url(r'^child/$', views.child, name='child', kwargs={'child_id': None}),
    url(r'^child/(?P<child_id>[0-9]+)', views.child),
    url(r'^media/lectures/(?P<file_name>.*)', views.download, name='download', kwargs={'path': 'media/lectures/'}),
    url(r'^media/assignments/(?P<file_name>.*)', views.download, name='download', kwargs={'path': 'media/assignments/'}),
    url(r'^lectures/$', views.lectures, name='lectures', kwargs={'lec_id': None}),
    url(r'^lectures/(?P<lec_id>[0-9]+)', views.lectures, name='lectures'),
    url(r'^assignments/$', views.assignments, name='assignments', kwargs={'subject_id': None}),
    url(r'^assignments/(?P<subject_id>[0-9]+)', views.assignments, name='assignments'),
    url(r'^assignments/solve/(?P<task_id>[0-9]+)', views.assignments_solve, name='assignments_solve'),
    url(r'^assignments/solve/$', views.assignments_solve, kwargs={'task_id': None}),
    url(r'^save_assignment/', views.save_assignment, name='save_assignment'),
    url(r'^attendance/$', views.attendance, name='attendance', kwargs={'child_id': None}),
    url(r'^attendance/(?P<child_id>[0-9]+)', views.attendance),
    url(r'^grades/$', views.grades, name='grades', kwargs={'child_id': None}),
    url(r'^grades/(?P<child_id>[0-9]+)', views.grades),
    url(r'^manage_attendance/$', views.manage_attendance, name='manage_attendance', kwargs={'class_id': None}),
    url(r'^manage_attendance/(?P<class_id>[0-9]+)', views.manage_attendance),
    url(r'^save_attendance/', views.save_attendance, name='save_attendance'),
    url(r'^manage_grades/$', views.manage_grades, name='manage_grades', kwargs={'class_id': None}),
    url(r'^manage_grades/(?P<class_id>[0-9]+)', views.manage_grades),
    url(r'^save_grades/', views.save_grades, name='save_grades'),
    url(r'^view_assignments/$', views.view_assignments, name='view_assignments', kwargs={'class_id': None, 'student_id': None}),
    url(r'^view_assignments/(?P<class_id>[0-9]+)$', views.view_assignments, kwargs={'student_id': None}),
    url(r'^view_assignments/(?P<class_id>[0-9]+)/(?P<student_id>[0-9]+)', views.view_assignments),
]
