# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 14:05
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import home.views


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day1', models.NullBooleanField(verbose_name='Day 1')),
                ('day2', models.NullBooleanField(verbose_name='Day 2')),
                ('day3', models.NullBooleanField(verbose_name='Day 3')),
                ('day4', models.NullBooleanField(verbose_name='Day 4')),
                ('day5', models.NullBooleanField(verbose_name='Day 5')),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(20), home.views.validate_nonzero])),
                ('num', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(20), home.views.validate_nonzero])),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject1mid', models.PositiveIntegerField(default=None, null=True, validators=[django.core.validators.MaxValueValidator(100), home.views.validate_nonzero], verbose_name='Subject 1 Midterm')),
                ('subject1final', models.PositiveIntegerField(default=None, null=True, validators=[django.core.validators.MaxValueValidator(100), home.views.validate_nonzero], verbose_name='Subject 1 Final')),
                ('subject1practical', models.PositiveIntegerField(default=None, null=True, validators=[django.core.validators.MaxValueValidator(100), home.views.validate_nonzero], verbose_name='Subject 1 Practical')),
                ('subject2mid', models.PositiveIntegerField(default=None, null=True, validators=[django.core.validators.MaxValueValidator(100), home.views.validate_nonzero], verbose_name='Subject 2 Midterm')),
                ('subject2final', models.PositiveIntegerField(default=None, null=True, validators=[django.core.validators.MaxValueValidator(100), home.views.validate_nonzero], verbose_name='Subject 2 Final')),
                ('subject2practical', models.PositiveIntegerField(default=None, null=True, validators=[django.core.validators.MaxValueValidator(100), home.views.validate_nonzero], verbose_name='Subject 2 Practical')),
                ('subject3mid', models.PositiveIntegerField(default=None, null=True, validators=[django.core.validators.MaxValueValidator(100), home.views.validate_nonzero], verbose_name='Subject 3 Midterm')),
                ('subject3final', models.PositiveIntegerField(default=None, null=True, validators=[django.core.validators.MaxValueValidator(100), home.views.validate_nonzero], verbose_name='Subject 3 Final')),
                ('subject3practical', models.PositiveIntegerField(default=None, null=True, validators=[django.core.validators.MaxValueValidator(100), home.views.validate_nonzero], verbose_name='Subject 3 Practical')),
                ('subject4mid', models.PositiveIntegerField(default=None, null=True, validators=[django.core.validators.MaxValueValidator(100), home.views.validate_nonzero], verbose_name='Subject 4 Midterm')),
                ('subject4final', models.PositiveIntegerField(default=None, null=True, validators=[django.core.validators.MaxValueValidator(100), home.views.validate_nonzero], verbose_name='Subject 4 Final')),
                ('subject4practical', models.PositiveIntegerField(default=None, null=True, validators=[django.core.validators.MaxValueValidator(100), home.views.validate_nonzero], verbose_name='Subject 4 Practical')),
                ('subject5mid', models.PositiveIntegerField(default=None, null=True, validators=[django.core.validators.MaxValueValidator(100), home.views.validate_nonzero], verbose_name='Subject 5 Midterm')),
                ('subject5final', models.PositiveIntegerField(default=None, null=True, validators=[django.core.validators.MaxValueValidator(100), home.views.validate_nonzero], verbose_name='Subject 5 Final')),
                ('subject5practical', models.PositiveIntegerField(default=None, null=True, validators=[django.core.validators.MaxValueValidator(100), home.views.validate_nonzero], verbose_name='Subject 5 Practical')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.Classroom')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('subject', models.CharField(default=None, max_length=50)),
                ('description', models.CharField(default=None, max_length=1000)),
                ('file', models.FileField(default=None, upload_to='./lectures/')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.Classroom')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=1, max_length=6)),
                ('phone', models.PositiveIntegerField()),
                ('mail', models.EmailField(max_length=100)),
                ('username', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=1, max_length=6)),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(20), home.views.validate_nonzero])),
                ('address', models.CharField(max_length=250)),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(20), home.views.validate_nonzero])),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.Classroom')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Parent')),
                ('username', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=1, max_length=6)),
                ('username', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='grade',
            name='student',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.Student'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='subject1teacher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.Teacher'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='subject2teacher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.Teacher'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='subject3teacher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.Teacher'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='subject4teacher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.Teacher'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='subject5teacher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.Teacher'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.Classroom'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.Student'),
        ),
    ]
