# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 14:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import home.views


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_lecture_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='num',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(15), home.views.validate_nonzero]),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='year',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(6), home.views.validate_nonzero]),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(15), home.views.validate_nonzero]),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(6), home.views.validate_nonzero]),
        ),
    ]
