# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 17:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20170512_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='student',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
