# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='day1',
            field=models.NullBooleanField(verbose_name='Sunday'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='day2',
            field=models.NullBooleanField(verbose_name='Monday'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='day3',
            field=models.NullBooleanField(verbose_name='Tuesday'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='day4',
            field=models.NullBooleanField(verbose_name='Wednesday'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='day5',
            field=models.NullBooleanField(verbose_name='Thursday'),
        ),
    ]
