# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 20:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20170512_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='subject1teacher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.Teacher', verbose_name='Arabic'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='subject2teacher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.Teacher', verbose_name='Maths'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='subject3teacher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.Teacher', verbose_name='English'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='subject4teacher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.Teacher', verbose_name='Physics'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='subject5teacher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.Teacher', verbose_name='Chmeistry'),
        ),
    ]
