# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 21:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import home.views


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20170512_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='subject1final',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(100), home.views.validate_nonzero], verbose_name='Arabic Final'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='subject1mid',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(100), home.views.validate_nonzero], verbose_name='Arabic Midterm'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='subject1practical',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(100), home.views.validate_nonzero], verbose_name='Arabic Practical'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='subject2final',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(100), home.views.validate_nonzero], verbose_name='Maths Final'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='subject2mid',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(100), home.views.validate_nonzero], verbose_name='Maths Midterm'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='subject2practical',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(100), home.views.validate_nonzero], verbose_name='Maths Practical'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='subject3final',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(100), home.views.validate_nonzero], verbose_name='English Final'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='subject3mid',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(100), home.views.validate_nonzero], verbose_name='English Midterm'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='subject3practical',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(100), home.views.validate_nonzero], verbose_name='English Practical'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='subject4final',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(100), home.views.validate_nonzero], verbose_name='Physics Final'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='subject4mid',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(100), home.views.validate_nonzero], verbose_name='Physics Midterm'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='subject4practical',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(100), home.views.validate_nonzero], verbose_name='Physics Practical'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='subject5final',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(100), home.views.validate_nonzero], verbose_name='Chemistry Final'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='subject5mid',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(100), home.views.validate_nonzero], verbose_name='Chemistry Midterm'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='subject5practical',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(100), home.views.validate_nonzero], verbose_name='Chemistry Practical'),
        ),
    ]
