# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20170512_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='subject',
            field=models.CharField(blank=True, choices=[('Arabic', 'Arabic'), ('Maths', 'Maths'), ('English', 'English'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry')], default=None, max_length=50, null=True),
        ),
    ]
