# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20170513_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('subject', models.CharField(blank=True, choices=[('Arabic', 'Arabic'), ('Maths', 'Maths'), ('English', 'English'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry')], default=None, max_length=50, null=True)),
                ('file', models.FileField(default=None, upload_to='./assignments/')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.Classroom')),
            ],
        ),
    ]
