# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solved_Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=1000)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Student')),
            ],
        ),
    ]
