# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20170513_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='classroom',
        ),
        migrations.AddField(
            model_name='assignment',
            name='classroom',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='home.Classroom'),
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='classroom',
        ),
        migrations.AddField(
            model_name='lecture',
            name='classroom',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='home.Classroom'),
        ),
    ]
