# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20170514_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='classroom',
            field=models.ManyToManyField(blank=True, default=None, to='home.Classroom'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='classroom',
            field=models.ManyToManyField(blank=True, default=None, to='home.Classroom'),
        ),
    ]
